# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: xxx
google_analytics: xxx
title: ifengling

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 随写's blog  —— 记录安全学习点滴

description: blingblingbling
author:
  name: 慢慢
  email: yiranhlf@gmail.com
  github: ifengling
  twitter: ifengling
  pinterest: 
  linkedin: 
  bio: 道阻且长，行则将至
 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
